/*
	Copyright 1982
	Alcyon Corporation
	8716 Production Ave.
	San Diego, Ca.  92121

	@(#)ctype - Apr 28, 1983
*/

#include <ctype.h>

char _ctype[] = { 
 _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL,
 _WHTSP|_CNTRL, _WHTSP|_CNTRL, _WHTSP|_CNTRL, _WHTSP|_CNTRL, _WHTSP|_CNTRL, 
 _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, 
 _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, _CNTRL, 
 _WHTSP|_BSPACE|_SPACE, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, 
 _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT,
 _DIGIT|_HEXDEC, _DIGIT|_HEXDEC, _DIGIT|_HEXDEC, _DIGIT|_HEXDEC, 
 _DIGIT|_HEXDEC, _DIGIT|_HEXDEC, _DIGIT|_HEXDEC, _DIGIT|_HEXDEC,
 _DIGIT|_HEXDEC, _DIGIT|_HEXDEC, _PUNCT, _PUNCT, _PUNCT, _PUNCT, 
 _PUNCT, _PUNCT, _PUNCT, _UPPER|_HEXDEC, _UPPER|_HEXDEC, _UPPER|_HEXDEC,
 _UPPER|_HEXDEC, _UPPER|_HEXDEC, _UPPER|_HEXDEC, _UPPER, _UPPER, 
 _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, 
 _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, _UPPER, 
 _UPPER, _UPPER, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, _PUNCT, 
 _LOWER|_HEXDEC, _LOWER|_HEXDEC, _LOWER|_HEXDEC, _LOWER|_HEXDEC, 
 _LOWER|_HEXDEC, _LOWER|_HEXDEC, _LOWER, _LOWER, _LOWER, _LOWER, 
 _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, 
 _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, _LOWER, 
 _PUNCT, _PUNCT, _PUNCT, _PUNCT, _CNTRL, 
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,
 _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII,  _NASCII
};

