/*	standard header file for c86	std.h	3/3/81
*/

#define NULL 0
#define EOF -1
#define STDIN 1
#define STDOUT 2
#define STDERR 3
#define AREAD 0		/* ascii read */
#define AWRITE 1	/* ascii write */
#define AUPDATE 2	/* ascii update (take care with this one) */
#define BREAD 3		/* binary update */
#define BWRITE 4	/* binary write */
#define BUPDATE 5	/* binary update */
#define FILE int

/*	end of standard header file
*/
