
	include cpyright.def

;*****************************************************
;*
;*	BDOS - Basic Disk Operating System
;*
;*****************************************************

	eject ! include equ.bdo		; symbol definitions
	eject ! include system.def
	eject ! include pd.def
	eject ! include err.def
	eject ! include qd.def
	eject ! include modfunc.def
	eject ! include xioscb.def
	eject ! include bdosif.bdo	; system initialization
	eject ! include file1.bdo	; file system part 1
	eject ! include file2.bdo	; file system part 2
	eject ! include file3.bdo	; file system part 3
	eject ! include file4.bdo	; file system part 4
	eject ! include patch.cod
	eject ! include uda.fmt		; User Data area
	eject ! include sysdat.fmt
	eject ! include data.bdo
	end
