	DSEG

public msg9120,msg9125,msg9135,msg9140,msg9145,msg9155,msg9160,msg9190
public msg9195,msg9250,msg9255,msg9485,msg9490,msg9495,msg9500,msg9505

;;
msg9120 db '0123456789ABCDEF'
;;
msg9125 db 'ERROR:  $',0
;;
msg9135 db 'Reading file:  $'
;;
msg9140 db 'Writing file:  $'
;;
msg9145 db 'Directory full$',0
;;
msg9155 db 'a',0
;;
msg9160 db 'z',0
;;
msg9190 db '#',0
;;
msg9195 db 'H',0
;;
msg9250 db 'Must be a Hex or Decimal number$'
;;
msg9255 db 'Unable to open file $',0
;;
msg9485 db '[',0
;;
msg9490 db ']',0
;;
msg9495 db 'Loader base must be specified.$',0
;;
msg9500 db 0dh,0ah,'*** CCP/M SYSTEM LOADER GENERATION DONE ***',0dh,0ah,'$',0
	db 'DRI$',0
;;
msg9505 db 'Drive Table must contain at least 1 DPH address.$'
