mac b:ddt1asm $$pp+s
era b:ddt1asm0.hex
ren b:ddt1asm0.hex=b:ddt1asm.hex
mac b:ddt1asm $$pzsz+r
era b:ddt1asm1.hex
ren b:ddt1asm1.hex=b:ddt1asm.hex
mac b:ddt2mon $$pp+s
era b:ddt2mon0.hex
ren b:ddt2mon0.hex=b:ddt2mon.hex
mac b:ddt2mon $$pzsz+r
era b:ddt2mon1.hex
ren b:ddt2mon1.hex=b:ddt2mon.hex
pip b:relddt0.hex=b:ddt1asm0.hex[i],b:ddt2mon0.hex[h]
pip b:relddt1.hex=b:ddt1asm1.hex[i],b:ddt2mon1.hex[h]
pip b:relddt.hex=b:relddt0.hex,b:relddt1.hex
genmod b:relddt.hex b:relddt.com
genhex b:relddt 100
era b:relddt0.hex
ren b:relddt0.hex=b:relddt.hex
genhex b:relddt 200
era b:relddt1.hex
ren b:relddt1.hex=b:relddt.hex
mac b:ddt0mov $$pp+s
era b:ddt0mov0.hex
ren b:ddt0mov0.hex=b:ddt0mov.hex
mac b:ddt0mov $$pzsz+r
era b:ddt0mov1.hex
ren b:ddt0mov1.hex=b:ddt0mov.hex
pip b:relddt0.hex=b:relddt0.hex[i],b:ddt0mov0.hex[h]
pip b:relddt1.hex=b:relddt1.hex[i],b:ddt0mov1.hex[h]
pip b:relddt.hex=b:relddt0.hex,b:relddt1.hex
genmod b:relddt.hex b:rdt.prl $$z1500
