era b:*.lst
era b:*.bak
isdd
;plm80 :f1:$1.plm debug nolist
;era b:*.lst
link :f1:$1.obj,:f1:x0100,plm80.lib to :f1:$11.mod
locate :f1:$11.mod code(0100H) stacksize(100)
era b:$11.mod
objhex :f1:$11 to :f1:$11.hex
link :f1:$1.obj,:f1:x0200,plm80.lib to :f1:$12.mod
era b:$1.obj
locate :f1:$12.mod code(0200H) stacksize(100)
era b:$12.mod
objhex :f1:$12 to :f1:$12.hex
era b:$12
cpm
;objcpm b:$11
era b:$1*.
;pip lst:=b:$11.sym[pt8]
;pip lst:=b:$11.lin[pt8]
;pip lst:=nul:[p]
era b:*.lin
era b:*.sym
pip b:$1.hex=b:$11.hex,b:$12.hex
era b:$11.hex
era b:$12.hex
genmod b:$1.hex b:$1.prl $$1000
era b:*.hex
