$ set noon
$ vsend CEXPR.C
$ vsend ICODE.H
$ vsend INIT.C
$ vsend LEX.C
$ vsend LINK.SUB
$ vsend LIST.COM
$ vsend MACHINE.11
$ vsend MACHINE.68K
$ vsend MACHINE.H
$ vsend MACHINE.VAX
$ vsend MACRO.C
$ vsend MAIN.C
$ vsend MAKE.SUB
$ vsend PREPROC.H
$ vsend SEND11.SUB
$ vsend UTIL.C
$ vsend VMAKE.COM
$ vsend done
