$ set noon
$ vsend CPUTC.C
$ vsend CREAT.C
$ vsend DUP.C
$ vsend GETC.C
$ vsend GETCHAR.C
$ vsend GETCVMS.C
$ vsend IODEC.H
$ vsend KLIB.H
$ vsend MAKE.COM
$ vsend MAKE.SUB
$ vsend OPEN.C
$ vsend PORTAB.H
$ vsend PUTC.C
$ vsend PUTCHAR.C
$ vsend PUTCVMS.C
$ vsend SEEK.C
$ vsend SEND4.SUB
$ vsend STRCMP.C
$ vsend UP4.SUB
$ vsend VMAKE.COM
$ vsend done
