$ set def [steve.cpm68k.c.fparser]
$ diff DECL.C [-.parser]DECL.C
$ diff EXPR.C [-.parser]EXPR.C
$ diff ICODE.C [-.parser]ICODE.C
$ diff INTERF.C [-.parser]INTERF.C
$ diff LEX.C [-.parser]LEX.C
$ diff MAIN.C [-.parser]MAIN.C
$ diff STMT.C [-.parser]STMT.C
$ diff TABL.C [-.parser]TABL.C
$ diff VERSION.C [-.parser]VERSION.C
$ diff ICODE.H [-.parser]ICODE.H
$ diff PARSER.H [-.parser]PARSER.H
