$ set noon
$ vsend DECL.C
$ vsend EXPR.C
$ vsend ICODE.C
$ vsend INTERF.C
$ vsend LEX.C
$ vsend MAIN.C
$ vsend STMT.C
$ vsend TABL.C
$ vsend VERSION.C
$ vsend ICODE.H
$ vsend PARSER.H
$ vsend machine.68k
$ vsend LINK.SUB
$ vsend MAKE.SUB
