;
;
;	THIS SUBMIT FILE WILL BUILD AN XIOS.CON MODULE
;	FOR THE SAMPLE CONCURRENT CP/M 3.1 COMPUPRO XIOS.
;	2/17/84
;
;
rasm86 headentr $lo
;
rasm86 ctc $lo
rasm86 pic $lo
rasm86 intvec $lo
rasm86 np_8087 $lo
rasm86 tick $lo
;
rasm86 conin $lo
rasm86 serin $lo
rasm86 conout $lo
rasm86 serout $lo
rasm86 servar $lo
;
rasm86 i3int $lo
rasm86 ssint $lo
;
rasm86 vscreen $lo
rasm86 switch $lo
;
rasm86 pcmode $lo
rasm86 statlin $lo
rasm86 list $lo
;
rasm86 vccb $lo
rasm86 serdata $lo
;
rasm86 dentry $lo
rasm86 fd $lo
rasm86 hdisk $lo
rasm86 reskew $lo
rasm86 mdisk $lo
rasm86 dpbs $lo
;
era *.lst
;
; LINK86 LOOKS FOR AN INPUT FILE "XIOS.INP"
; (SEE HEADENTR.A86)
;
link86 xios[i
;
ren xios.con=xios.cmd
