
title	'List Device module'

;******************************************
;					  *
;	LIST DEVICE MODULE		  *
;	Last changed : 1/30/84		  *
;					  *
;******************************************

	dseg

public	lcb0

extrn   oq7desc:byte
extrn	oq8desc:byte

	cseg

public	io_listst, io_list

extrn	serial_out:near

;=========
io_listst:	; Function 3:  List Status
;=========
;	input:	DL = list device number
;	output:	AL = 0ffh if ready
;		   = 000h if not ready

	xor al,al
	ret			;back to caller

;=======
io_list:	; Function 4: List Output
;=======
;	input:	CL = character
;		dl = list device number
;	output:	None

	cmp dl, 0 ! je list0
	   mov bx, offset oq7desc
	   jmps list1
list0:
	mov bx, offset oq8desc
list1:
	call serial_out

	ret

	dseg

lcb0	dw	0,0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource

lcb1	dw	0,0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource

	end

