
title	'VCCBs for CCP/M'

;****************************************
;					*
;	VIRTUAL CONSOLE CONTROL BLOCKS  *
;	Last changed: 2/13/84		*
;					*
;****************************************

include	system.lib

public	vccb0
public	vccb_tbl,vrtl_phy

cgroup	group	vccb_seg

	dseg

vccb_tbl	dw	offset vccb0	; Pcon 0
		dw	offset vccb1
		dw	offset vccb2
		dw	offset vccb3

		dw	offset vccb4	; Pcon 1
		dw	offset vccb5
		dw	offset vccb6
		dw	offset vccb7

vrtl_phy	db	0
		db	0
		db	0
		db	0
		db	1
		db	1
		db	1
		db	1

vccb_seg		dseg	para

vccb0	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	0		;physical console number
	db	0		;virtual console number
	dw	0		;reserved
	dw	0000h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	offset	vccb1	; virtual console link
	dw	0		;reserved

vccb1	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	0		;physical console number
	db	1		;virtual console number
	dw	0		;reserved
	dw	0002h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	offset	vccb2	; virtual console link
	dw	0		;reserved

vccb2	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	0		;physical console number
	db	2		;virtual console number
	dw	0		;reserved
	dw	0002h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	offset vccb3	; virtual console link
	dw	0		;reserved

vccb3	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	0		;physical console number
	db	3		;virtual console number
	dw	0		;reserved
	dw	0002h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	0		; last Vcon on Pcon 1
	dw	0		;reserved

eject

vccb4	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	1		;physical console number
	db	4		;virtual console number
	dw	0		;reserved
	dw	0000h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	offset vccb5	; link
	dw	0		;reserved

vccb5	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	1		; physical console number
	db	5		;virtual console number
	dw	0		;reserved
	dw	0002h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	offset vccb6	; link
	dw	0		;reserved

vccb6	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	1		;physical console number
	db	6		;virtual console number
	dw	0		;reserved
	dw	0002h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	offset vccb7	; link
	dw	0		;reserved

vccb7	dw	0		;owner
	dw	0,0,0		;reserved
	db	0ffh,0ffh	;mimic, msource
	db	1		; physical console number
	db	7		;virtual console number
	dw	0		;reserved
	dw	0002h		;state flags
	dw	10		;max buffer size K bytes
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0,0		;reserved
	dw	0,0		;reserved
	dw	0		; link, last vcon on pcon 1
	dw	0		;reserved

	end

