$ mcr flx 'p1'/ze/do
$ set def [.lib]
$ mcr flx 'p1'[1,1]/do/im=clib./im/rs,s.o,w.o,libe.a,libf.a
$ mcr flx 'p1'[1,2]/do/-rw=*.h/rs
$ set def [-.bin]
$ mcr flx 'p1'[1,3]/do/-rw=*.exe,*.com,as68init.,install.doc/rs
$ set def [-.cpm]
$ mcr flx 'p1'[1,4]/do/-rw/im=ldrlib/im/rs,cpmlib
$ mcr flx 'p1'[1,5]/do/-rw=*.c,*.s,*.h,*.sub,*.com/rs
$ set def [-.com]
$ mcr flx 'p1'[1,6]/do/-rw=*.*/rs
