/****************************************************************/
/*                                                              */
/*      Define BDOS Function Codes                              */
/*                                                              */
/****************************************************************/
 
#define SYSRESET 0
#define CONIN   1
#define CONOUT  2
#define READIN  3
#define PUNOUT  4
#define LISTOUT 5
#define DCONIO  6
#define GETIOB  7
#define SETIOB  8
#define PRNTSTR 9
#define READBUF 10
#define CONSTAT 11
#define GETVER  12
#define RESETDSK 13
#define SELDSK  14
#define OPEN    15
#define CLOSE   16      
#define SRCHFST 17
#define SRCHNXT 18
#define DELETE  19
#define READSEQ 20
#define WRITSEQ 21
#define MAKEFILE 22     
#define RENAME  23
#define GTLOGIN 24
#define CURDSK  25
#define SETDMA  26
#define WRTPROT 28
#define GETROV  29
#define SETATTR 30
#define GETDPB  31
#define USERCD  32
#define READRND 33
#define WRITRND 34
#define FILESIZ 35
#define SETRND  36
#define RESTDRV 37
#define WRANDZF 40
#define GETFREE 46
#define DBIOSCL 50
#define PGMLOAD 59
ne PGMLOAD 59
