eject ! include cpyright.def

;*****************************************************
;*
;*	System Data Area - Initialized Data
;*
;*****************************************************
eject ! include system.def
eject ! include pd.def
eject ! include qd.def
eject ! include modfunc.def
eject ! include system.dat
eject
cpm	equ	false
mpm	equ	true
include data.bdo
eject ! end
