CC = c68
OBJS = cexpr.o lex.o macro.o main.o util.o
CFLAGS = -L
LIB = -l6 -l7

st: ${OBJS}
	@mkver -e "preprocessor - "
	${CC} ${CFLAGS} -n -r ${OBJS} version.c ${LIB} -o c68.st
	@setstack c68.st 8192 8192 ;size c68.st

c68:	${OBJS}
	@mkver -e "preprocessor - "
	${CC} ${CFLAGS} -r ${OBJS} version.c ${LIB} -o c68.68
	@setstack c68.68 8192 8192 ;size c68.68
