rx?iJiPiii?
i$M` COPYRIGHT (C) 1981, DIGITAL RESEARCH DDT86 1.2 08/20/82 AXBXCXDXSPBPSIDICSDSSSESIPODITSZAPC	
CSDSESSSX1X2X3X4
CANNOT CLOSE
INSUFFICIENT MEMORY
NO SPACE
MEMORY REQUEST DENIED
NO FILE  START      END
VERIFY ERROR AT 
DISK WRITE ERROR ~@"?*dQ`Q`xpn+@@X9s$C>4,
@t<@v0@H?os$0
*hB
C|i	&k.\.	&PX%&.#bHzP<?vt{huh1>:h	h,t@PsFh4<07r2~h7>h> t:\h,|<?h*0-hshXh|<
t]<;tY,Ar
