mac b:dump $$szhz
pip b:mpmugg.tex=b:mpmugghd.tex,b:disclaim.lib,b:dump.prn[t8d70l],b:break.tex
era b:dump.prn
tex b:mpmugg b:
era b:mpmugg.tex
pip lst:=b:mpmugg.prn[t8]
era b:mpmugg.prn
mac b:type $$szhz
pip b:mpmugh.tex=b:mpmughhd.tex,b:disclaim.lib,b:type.prn[t8d70l],b:break.tex
era b:type.prn
tex b:mpmugh b:
era b:mpmugh.tex
pip lst:=b:mpmugh.prn[t8]
era b:mpmugh.prn
mac b:xios $$szhz
pip b:mpmugi.tex=b:mpmugihd.tex,b:disclaim.lib,b:xios.prn[t8d70l],b:break.tex
era b:xios.prn
tex b:mpmugi b:
era b:mpmugi.tex
pip lst:=b:mpmugi.prn[t8]
era b:mpmugi.prn
tex b:mpmugj-k b:
pip lst:=b:mpmugj-k.prn[t8]
era b:*.prn
