b:tex b:mpmfs0 b:
pip lst:=b:mpmfs0.prn[d79]
b:tex b:mpmfs1 b:
pip lst:=b:mpmfs1.prn[d79]
mac b:bios $$+s+m
pip b:mpmfs2.tex=b:mpmfs2hd.tex,b:bios.prn,b:break.tex
era b:bios.prn
era b:bios.hex
b:tex b:mpmfs2 b:
pip lst:=b:mpmfs2.prn[d79]
era b:mpmfs2.*
mac b:dump $$+s
pip b:mpmfs3.tex=b:mpmfs3hd.tex,b:dump.prn,b:break.tex
era b:dump.hex
era b:dump.prn
b:tex b:mpmfs3 b:
pip lst:=b:mpmfs3.prn[d79]
era b:mpmfs3.*
mac b:type $$+s
pip b:mpmfs4.tex=b:mpmfs4hd.tex,b:type.prn,b:break.tex
era b:type.hex
era b:type.prn
b:tex b:mpmfs4 b:
pip lst:=b:mpmfs4.prn[d79]
era b:mpmfs4.*
