;mac a:dump $$szhz
;pip a:mpmugg.tex=a:mpmugghd.tex,a:disclaim.lib,a:dump.prn[t8d70l],a:break.tex
;era a:dump.prn
;tex a:mpmugg b:
;era a:mpmugg.tex
;;pip lst:=b:mpmugg.prn
;;era b:*.prn
;mac a:type $$szhz
;pip a:mpmugh.tex=a:mpmughhd.tex,a:disclaim.lib,a:type.prn[t8d70l],a:break.tex
;era a:type.prn
;tex a:mpmugh b:
;era a:mpmugh.tex
;;pip lst:=b:mpmugh.prn
;;era b:*.prn
mac a:xios $$szhz
pip a:mpmugi.tex=a:mpmugihd.tex,a:disclaim.lib,a:xios.prn[t8d70l],a:break.tex
era a:xios.prn
tex a:mpmugi b:
era a:mpmugi.tex
;pip lst:=b:mpmugi.prn
;era b:*.prn
tex a:mpmugj-k b:
;pip lst:=b:mpmugj-k.prn[t8]
;era b:*.prn
tex a:mpmugidx b:
;pip lst:=b:mpmugidx.prn[t8]
;era b:*.prn
