single b:
tex a:mpmug0 b:
;pip lst:=b:mpmug0.prn
;era b:*.prn
tex a:mpmug1 b:
;pip lst:=b:mpmug1.prn
;era b:*.prn
tex a:mpmug20 b:
;pip lst:=b:mpmug20.prn
;era b:*.prn
tex a:mpmug21 b:
;pip lst:=b:mpmug21.prn
;era b:*.prn
tex a:mpmug22 b:
;pip lst:=b:mpmug22.prn
;era b:*.prn
tex a:mpmug23 b:
;pip lst:=b:mpmug23.prn
;era b:*.prn
tex a:mpmug24 b:
;pip lst:=b:mpmug24.prn
;era b:*.prn
;
;type ^C
;then remove disk from drive b:
;place a blank single density disk in drive b:
;then enter: sub mpmug+
;
