mac b:bios $$+s+m
pip b:mpmfs2.tex=b:mpmfs2hd.tex,b:bios.prn,b:break.tex
era b:bios.prn
era b:bios.hex
b:tex b:mpmfs2 b:
era b:b:mpmfs2.tex
mac b:dump $$+s
pip b:mpmfs3.tex=b:mpmfs3hd.tex,b:dump.prn,b:break.tex
era b:dump.hex
era b:dump.prn
b:tex b:mpmfs3 b:
era b:mpmfs3.tex
mac b:type $$+s
pip b:mpmfs4.tex=b:mpmfs4hd.tex,b:type.prn,b:break.tex
era b:type.hex
era b:type.prn
b:tex b:mpmfs4 b:
era b:mpmfs4.tex
