   title  'M-4 CPM-86/80 Basic I/O System'

;*********************************************
;*					     *
;*      M-Four Basic I/O System 	     *
;*      for CPM.SYS			     *
;*					     *
;*********************************************

	nolist
	include m4equ.lib
	include m4jump.lib
	list

;*********************************************
;*					     *
;* Loader_bios is true if assembling the     *
;* LOADER BIOS, otherwise BIOS is for the    *
;* CPM.SYS file.                             *
;*					     *
;*********************************************

loader_bios	equ	false
cal		equ	false
special		equ	true		;for hybrid machine

	include m4bios.lib

	END
    