$ set noon
$ vsend CANON.C
$ vsend CODEGEN.C
$ vsend CSKELS.C
$ vsend INTERF.C
$ vsend MAIN.C
$ vsend OPTAB.C
$ vsend PUTEXPR.C
$ vsend SMATCH.C
$ vsend SUCOMP.C
$ vsend TABL.C
$ vsend UTIL.C
$ vsend VERSION.C
$ vsend CGEN.H
$ vsend CSKEL.H
$ vsend ICODE.H
$ vsend machine.68k
$ vsend LINK.SUB
$ vsend MAKE.SUB
$ vsend done
