$ set noon
$ vsend DIR.C
$ vsend EXPR.C
$ vsend MAIN.C
$ vsend MISC.C
$ vsend PASS1A.C
$ vsend PASS2.C
$ vsend QSORT.C
$ vsend STRNCMP.C
$ vsend SYMT.C
$ vsend VERSION.C
$ vsend AS68.H
$ vsend COUT.H
$ vsend CTYPE.H
$ vsend MAKE.SUB
$ vsend RELINK.SUB
$ vsend ASTEST.S
$ vsend STARTUP.S
$ vsend MACHINE.11
$ vsend MACHINE.68K
$ vsend MACHINE.H
$ vsend MACHINE.VAX
$ vsend AS68INIT.
