$ set noon
$ vsend BDOSDEF.H
$ vsend BDOSIF.S
$ vsend BDOSMAIN.C
$ vsend BDOSREAD.C
$ vsend BIOSDEF.H
$ vsend BOOTER.S
$ vsend CPMLDR.C
$ vsend DSKUTIL.C
$ vsend FILEIO.C
$ vsend IOSYS.C
$ vsend LDRBIOS.S
$ vsend LDRIF.S
$ vsend LDRLIB.
$ vsend MAKE.SUB
$ vsend PKTIO.H
$ vsend PUTBOOT.S
$ vsend STDIO.H
$ vsend VMAKE.COM
$ vsend done
