$ set noon
$ vsend DECL.C
$ vsend EXPR.C
$ vsend ICODE.C
$ vsend ICODE.H
$ vsend INIT.C
$ vsend INTERF.C
$ vsend LEX.C
$ vsend LINK.SUB
$ vsend LIST.COM
$ vsend MACHINE.11
$ vsend MACHINE.68K
$ vsend MACHINE.H
$ vsend MACHINE.VAX
$ vsend MAIN.C
$ vsend MAKE.SUB
$ vsend PARSER.H
$ vsend SEND12.SUB
$ vsend STMT.C
$ vsend TABL.C
$ vsend UP12.SUB
$ vsend VERSION.C
$ vsend VMAKE.COM
$ vsend done
