era b:*.spr
era b:*.bak
era b:*.hex
mac b:bdos $$+s
pip lst:=b:bdos.prn[lt8]
pip lst:=nul:[p]
era b:bdos.prn
era b:bdos.hx0
ren b:bdos.hx0=b:bdos.hex
mac b:bdos $$+rpzsz
pip b:bdos.hex=b:bdos.hx0,b:bdos.hex
genmod b:bdos.hex b:bdos.spr
era b:*.hex
era b:*.hx0
mac b:odos $$+s
pip lst:=b:odos.prn[lt8]
pip lst:=nul:[p]
era b:odos.prn
era b:odos.hx0
ren b:odos.hx0=b:odos.hex
mac b:odos $$+rpzsz
pip b:odos.hex=b:odos.hx0,b:odos.hex
genmod b:odos.hex b:odos.spr
era b:*.hex
era b:*.hx0
mac b:bnkbdos $$+s
pip lst:=b:bnkbdos.prn[lt8]
pip lst:=nul:[p]
era b:bnkbdos.prn
era b:bnkbdos.hx0
ren b:bnkbdos.hx0=b:bnkbdos.hex
mac b:bnkbdos $$+rpzsz
pip b:bnkbdos.hex=b:bnkbdos.hx0,b:bnkbdos.hex
genmod b:bnkbdos.hex b:bnkbdos.spr
era b:*.hex
era b:*.hx0
