;       title   'Bdos Interface, Bdos, Version 2.2 Feb, 1980'
;*****************************************************************
;*****************************************************************
;**                                                             **
;**			L o a d e r				**
;**   B a s i c    D i s k   O p e r a t i n g   S y s t e m    **
;**            I n t e r f a c e   M o d u l e                  **
;**                                                             **
;*****************************************************************
;*****************************************************************
;
;       Copyright (c) 1978, 1979, 1980
;       Digital Research
;       Box 579, Pacific Grove
;       California
;
;
;       5 september, 1980
;	smaller version of BDOS for CP/M-86 Loader	
;
;**********************************************
;
cpmsegment      equ     0	; base of CP/M-86
ldroffset       equ     0   	; offset of CPMLDR
bdosoffset      equ     400H    ; offset of LBDOS-86
biosoffset      equ     1200H   ; offset of LBIOS-86
bdoscodesize    equ     0B00H   ; size of BDOS code
;
eject ! include lbdosequ.a86	 ; symbol definition
eject ! include lbdosent.a86     ; entry module
eject ! include lbdosnew.a86     ; new 8086 BDOS functions
eject ! include lbdosio.a86      ; byte I/O module
eject ! include lbdosf1.a86      ; file system part 1
eject ! include lbdosf2.a86      ; file system part 2
eject ! include lbdosf3.a86      ; file system part 3
eject ! include lbdosdat.a86     ; data area
eject
;********************** end of BDOS ********************
end
