;
;			GENERATE XIOS.MPM
;
a86 xios
gencmd xios 8080
era xios.mpm
ren xios.mpm=xios.cmd
vax xios.lst $$atn
xref86 xios
vax xios.xrf $$atn
;
;			GENERATE LDMPM.H86
a86 ldmpm
xref86 ldmpm
vax ldmpm.lst $$atn
vax ldmpm.xrf $$atn
;
;			GENERATE LDBDOS.H86
a86 ldbdos
xref86 ldbdos
vax ldbdos.lst $$atn
vax ldbdos.xrf $$atn
;
;			GENERATE LDBIOS.H86
;
a86 ldbios
xref86 ldbios
vax ldbios.lst $$atn
vax ldbios.xrf $$atn
;
;			GENERATE MPMLDR.CMD
;
pip mpmldr.h86=ldmpm.h86,ldbdos.h86,ldbios.h86
gencmd mpmldr 8080 code[a0400]
;
