$ set noon
$ vsend BDOS.S
$ vsend BDOSFUNC.H
$ vsend CETACEAN.SUB
$ vsend DDTINC.H
$ vsend DISAS.H
$ vsend DOWN5.SUB
$ vsend LGCDEF.H
$ vsend LIST.COM
$ vsend MAKE.SUB
$ vsend OPTAB.H
$ vsend PANACEA.SUB
$ vsend SID03.C
$ vsend SID04.C
$ vsend SID05.C
$ vsend SID68K.C
$ vsend SID68K.DOK
$ vsend SIDDEF.H
$ vsend SIDFUN.C
$ vsend SIDLOAD.S
$ vsend STDIO.H
$ vsend UP5.SUB
$ vsend done
