
CC = c68
OBJS = decl.o expr.o icode.o init.o interf.o lex.o main.o 
OBJ2 = stmt.o tabl.o putexpr.o misc.o node.o symt.o
CFLAGS = -L -e
LIB = -l6 -lE -l7

st: ${OBJS} ${OBJ2}
	@mkver -e "parser - "
	${CC} -n ${CFLAGS} -r ${OBJS} ${OBJ2} version.c -o c068.st ${LIB}
	@setstack c068.st 8192 8192 ; size c068.st

C068: ${OBJS} ${OBJ2}
	@mkver -e "parser - "
	${CC} ${CFLAGS} -r ${OBJS} ${OBJ2} version.c -o c068.68 ${LIB}
	@setstack c068.68 8192 8192 ; size c068.68
