$ del ATOF.lis;*
$ del CEIL.lis;*
$ del ETOA.lis;*
$ del FABS.lis;*
$ del FFPTOF.lis;*
$ del FLOOR.lis;*
$ del FMOD.lis;*
$ del FPRINTF.lis;*
$ del FTOA.lis;*
$ del FTOFFP.lis;*
$ del FTOL.lis;*
$ del LTOF.lis;*
$ del PRINTF.lis;*
