pip a:=e:show.plm
seteof show.plm
isx
plm80 show.plm pagewidth(80) debug
era show.plm
link show.obj,x0100,plm80.lib to show1.mod
locate show1.mod code(0100H) stacksize(100)
era show1.mod
objhex show1 to show1.hex
link show.obj,x0200,plm80.lib to show2.mod
locate show2.mod code(0200H) stacksize(100)
era show2.mod
objhex show2 to show2.hex
era show2
cpm
objcpm show1
era show1.com
ren show.sym=show1.sym
ren show.lin=show1.lin
vax show.lst $$stan
vax show.sym $$stan
vax show.lin $$stan
pip show.hex=show1.hex,show2.hex
era show1.hex
era show2.hex
zero
genmod show.hex xshow.prl 
pip e:show.prl=a:xshow.prl
pip b:show.prl=a:xshow.prl
era *.hex
pip a:=e:stat.plm
seteof stat.plm
isx
plm80 stat.plm pagewidth(80) debug
era stat.plm
link stat.obj,x0100,plm80.lib to stat1.mod
locate stat1.mod code(0100H) stacksize(100)
era stat1.mod
objhex stat1 to stat1.hex
link stat.obj,x0200,plm80.lib to stat2.mod
locate stat2.mod code(0200H) stacksize(100)
era stat2.mod
objhex stat2 to stat2.hex
era stat2
cpm
objcpm stat1
era stat1.com
ren stat.sym=stat1.sym
ren stat.lin=stat1.lin
vax stat.lst $$stan
vax stat.sym $$stan
vax stat.lin $$stan
pip stat.hex=stat1.hex,stat2.hex
era stat1.hex
era stat2.hex
zero
genmod stat.hex xstat.prl 
pip e:stat.prl=a:xstat.prl
pip b:stat.prl=a:xstat.prl
era *.hex
pip a:=e:type.plm
seteof type.plm
isx
plm80 type.plm pagewidth(80) debug
era type.plm
link type.obj,x0100,plm80.lib to type1.mod
locate type1.mod code(0100H) stacksize(100)
era type1.mod
objhex type1 to type1.hex
link type.obj,x0200,plm80.lib to type2.mod
locate type2.mod code(0200H) stacksize(100)
era type2.mod
objhex type2 to type2.hex
era type2
cpm
objcpm type1
era type1.com
ren type.sym=type1.sym
ren type.lin=type1.lin
vax type.lst $$stan
vax type.sym $$stan
vax type.lin $$stan
pip type.hex=type1.hex,type2.hex
era type1.hex
era type2.hex
zero
genmod type.hex xtype.prl 
pip e:type.prl=a:xtype.prl
pip b:type.prl=a:xtype.prl
era *.sym
era *.lin
era *.lst
era xtype.prl
era xshow.prl
era xstat.prl
era *.hex
era *.obj
;end prla 1 2 3 submit
