;
;			GENERATE TMP.RSP
;
a86 tmp
gencmd tmp
era tmp.rsp
ren tmp.rsp=tmp.cmd
vax tmp.lst $$atn
xref86 tmp
vax tmp.xrf $$atn
;
;			GENERATE ECHO.RSP
;
a86 echo
gencmd echo
era echo.rsp
ren echo.rsp=echo.cmd
vax echo.lst $$atn
xref86 echo
vax echo.xrf $$atn
;
;			GENERATE CLOCK.RSP
;
a86 clock
gencmd clock
era clock.rsp
ren clock.rsp=clock.cmd
vax clock.lst $$atn
xref86 clock
vax clock.xrf $$atn
;
;			GENERATE SUBMIT.CMD
;
a86 submit
gencmd submit
vax submit.lst $$atn
xref86 submit
vax submit.xrf $$atn
;
;			GENERATE RANDOM.CMD
;
a86 random
gencmd random
vax random.lst $$atn
xref86 random
vax random.xrf $$atn 
;
