
CC = c68
OBJS = canon.o codegen.o interf.o main.o optab.o putexpr.o smatch.o sucomp.o \
	tabl.o util.o cskels.o
CFLAGS = -L -r
LIB = -l6

st: ${OBJS}
	@mkver -e "code generator - "
	${CC} ${CFLAGS} -n ${OBJS} version.c ${LIB} -o c168.st
	@setstack c168.st 8192 8192 ; size c168.st

c068: ${OBJS}
	@mkver -e "code generator - "
	${CC} ${CFLAGS} ${OBJS} version.c ${LIB} -o c168.68
	@setstack c168.68 8192 8192 ; size c168.68
