
	include cpyright.def

;*****************************************************
;*
;*	MP/M-86 character I/O Module
;*
;*****************************************************
	eject ! include system.def
	eject ! include modfunc.def
	eject ! include xioscb.def
	eject ! include pd.def
	eject ! include err.def
	eject ! include qd.def
	eject ! include acb.def
	eject ! include ccb.def
	eject ! include char.def
	eject ! include cioif.cio
	eject ! include console.cio
	eject ! include chario.cio
	eject ! include patch.cod
	eject ! include uda.fmt
	eject ! include sysdat.fmt
	eject ! end
