;MP/M-86 VAX utility backup disk #3 - mpmstat, sdir and gensys source
;
;writes on drive B, beware !
;
;up load plm-86 source, include files and submit files
;that compile into MP/M-86 utilities on the VAX 
;
;log into FRANK on the VAX before running this submit
;
user 0
mode b 0
dskreset
b:
;
vax $$a\set def [frank.mpm86.mpmstat]\
;
vax stsrsp.plm $$fans
vax stscmd.plm $$fans
vax stscom.plm $$fasn
;
vax mpmstat.com $$fans
;
vax rspasm.a86 $$fans
vax mcd.a86 $$fans
;
vax ccb.lit $$fans
vax comlit.lit $$fans
vax copyrt.lit $$fans
vax fcb.lit $$fans
vax flag.lit $$fans
vax mdsat.lit $$fans
vax proces.lit $$fans
vax qd.lit $$fans
vax sd.lit $$fans
vax uda.lit $$fans
;
vax $$a\set def [frank.mpm86.sdir]\
;
vax disp.plm $$fans
vax dpb80.plm $$fans
vax dpb86.plm $$fans
vax main.plm $$fans
vax main80.plm $$fasn
vax main86.plm $$fans
vax mon.plm $$fans
vax scan.plm $$fans
vax search.plm $$fans
vax sort.plm $$fans
vax timest.plm $$fans
vax util.plm $$fans
;
vax comlit.lit $$fans
vax copyrt.lit $$fans
vax dpb.lit $$fans
vax finfo.lit $$fans
vax format.lit $$fans
vax scan.lit $$fans
vax search.lit $$fans
vax vers.lit $$fans
vax xfcb.lit $$fans
;
vax scd.a86 $$fans
;
vax sdirall.com $$fasn
;
;vax $$a\set def [frank.mpm86.gensys]\
;
vax gs.plm $$fans
vax gl.plm $$fans
vax sd.plm $$fans
;
vax mcd.a86 $$fans
;
vax gsall.com $$fans
;
vax ccb.lit $$fans
vax copyrt.lit $$fans
vax sysdat.lit $$fans
;
;
dir
;
;
sdir
