;MP/M-86 VAX utility backup disk #2 - separate code and data programs
;
;writes on drive B, beware !
;
;up load plm-86 source, include files and submit files
;that compile into MP/M-86 utilities on the VAX 
;
;log into FRANK on the VAX before running this submit
;
user 0
mode b 0
dskreset
b:
;
vax $$a\set def [frank.mpm86.sepcd]
;
vax comlit.lit $$fans
vax copyrt.lit $$fans
vax dpb.lit $$fans
vax dpb86.plm $$fans
vax ed.plm $$fans
vax gemit.plm $$fans
vax gencmd.plm $$fans
vax gendef.com $$fans
vax gendef.plm $$fans
vax glit.plb $$fans
vax gpas.plb $$fans
vax gscan.plm $$fans
vax gtoken.plm $$fans
vax pip.plm $$fans
vax scd.a86 $$fans
vax scom.plm $$fans
vax sepall.com $$fans
vax smpmcmd.com $$fans
vax stat86.com $$fans
vax stat86.plm $$fans
;
;
dir b:
;
;
sdir b:
