;
;writes on drives A and B beware !
;
;up load plm-86 source, include files and submit files
;that compile into MP/M-86 utilities on the VAX 
;
;log into FRANK on the VAX before running this submit
;
user 0
mode a 0
mode b 0
a:
;
vax $$a\set def [frank.mpm86.mixcd]
;
;creating source on a:  disk #1
;
vax abort.plm $$fans
vax attach.plm $$fans
vax cons.plm $$fans
vax dir.plm $$fans
vax dskrst.plm $$fans
vax era.plm $$fans
vax eraq.plm $$fans
vax ren.plm $$fans
vax set.plm $$fans
vax show.plm $$fans
vax spool.plm $$fans
vax sspool.plm $$fans
vax tod.plm $$fasn
vax type.plm $$fans
;
vax mixcd.a86 $$fans
;
vax mixall.com $$fans
vax mpmcmd.com $$fans
;
vax copyrt.lit $$fans
vax flag.lit $$fans
vax mdsat.lit $$fans
vax proces.lit $$fans
vax qd.lit $$fans
vax sd.lit $$fans
vax uda.lit $$fans
;
;
;
dir a:
;
;
sdir a:
;
;
;
vax $$a\set def [frank.mpm86.sepcd]
;
;creating source on b: disk #2
dskreset
b:
;
vax ed.plm $$fans
vax pip.plm $$fans
vax stat86.plm $$fans
vax scom.plm $$fans
vax scd.a86 $$fans
vax smpmcmd.com $$fans
vax sepall.com $$fans
vax stat86.com $$fans
vax comlit.lit $$fans
vax dpb86.plm $$fans
vax dpb.lit $$fans
;
;
;
dir b:
;
;
sdir b:
;
;
;
vax $$a\set def [frank.mpm86.mpmstat]\
;
;creating source on a: disk #3
;
dskreset
a:
vax stsrsp.plm $$fans
vax stscmd.plm $$fans
vax stscom.plm $$fasn
;
vax mpmstat.com $$fans
;
vax rspasm.a86 $$fans
vax mcd.a86 $$fans
;
vax ccb.lit $$fans
vax comlit.lit $$fans
vax copyrt.lit $$fans
vax flag.lit $$fans
vax mdsat.lit $$fans
vax proces.lit $$fans
vax qd.lit $$fans
vax sd.lit $$fans
vax uda.lit $$fans
;
;
;
dir a:
;
;
sdir a:
;
;
;
vax $$a\set def [frank.mpm86.sdir]\
;
;creating source on b: disk #4
dskreset
b:
;
vax disp.plm $$fans
vax dpb80.plm $$fans
vax dpb86.plm $$fans
vax main.plm $$fans
vax main80.plm $$fasn
vax main86.plm $$fans
vax scan.plm $$fans
vax search.plm $$fans
vax sort.plm $$fans
vax timest.plm $$fans
vax util.plm $$fans
;
vax comlit.lit $$fans
vax dpb.lit $$fans
vax finfo.lit $$fans
vax format.lit $$fans
vax mon.lit $$fans
vax scan.lit $$fans
vax search.lit $$fans
vax vers.lit $$fans
vax xfcb.lit $$fans
;
vax scd.a86 $$fans
;
vax sdirall.com $$fasn
;
;
;
;
dir b:
;
;
sdir b:
;
;
;
;vax $$a\set def [frank.mpm86.gensys]\
;
;creating source on a: disk #5
dskreset
a:
;
vax gs.plm $$fans
vax gl.plm $$fans
vax sd.plm $$fans
;
vax mcd.a86 $$fans
;
vax gsall.com $$fans
;
vax ccb.lit $$fans
vax sysdat.lit $$fans
;
;
;
;
dir a:
;
;
sdir a:
;
;
;
;
;vax $$a\set def [frank.mpm86.asm86]
;
;creating source on b: disk #6
dskreset
b:
;
vax brexpr.plm $$fans
vax cm.plm $$fans
vax cm2.plm $$fans
vax cmac1.plm $$fans
vax cmac2.plm $$fans
vax cmac3.plm $$fans
vax cmac4.plm $$fans
vax cmac5.plm $$fans
vax cmsubr.plm $$fans
vax dline.plm $$fans
vax ermod.plm $$fans
vax expr.plm $$fans
vax files.plm $$fans
vax global.plm $$fans
vax instr.plm $$fans
vax io.plm $$fans
vax mainp.plm $$fans
vax mnem1.plm $$fans
vax mnem2.plm $$fans
vax mnem3.plm $$fans
vax mnem4.plm $$fans
vax outp.plm $$fans
vax predef.plm $$fans
vax print.plm $$fans
vax pseud1.plm $$fans
vax pseud2.plm $$fans
;
;
;
;
dir b:
;
;
sdir b:
;
;
;
;creating source on a: disk #7
;
dskreset
a:
;
vax scan.plm $$fans
vax subr1.plm $$fans
vax subr2.plm $$fans
vax symb.plm $$fans
vax text.plm $$fans
;
vax cm.lit $$fans
vax cmac.lit $$fans
vax cmacd.lit $$fans
vax dev.lit $$fans
vax equals.lit $$fans
vax ermod.lit $$fans
vax macro.lit $$fans
vax mnem.lit $$fans
vax outp.lit $$fans
vax struc.lit $$fans
;
vax cm.ext $$fans
vax cm2.ext $$fans
vax cmlink.ext $$fans
vax cmsubr.ext $$fans
vax dline.ext $$fans
vax ermod.ext $$fans
vax exglob.ext $$fans
vax expr.ext $$fans
vax files.ext $$fans
vax global.ext $$fans
vax instr.ext $$fans
vax io.ext $$fans
vax mglob.ext $$fans
vax mnem.ext $$fans
vax outp.ext $$fans
vax predef.ext $$fans
vax print.ext $$fans
vax pseud1.ext $$fans
vax pseud2.ext $$fans
vax scan.ext $$fans
vax subr1.ext $$fans
vax subr2.ext $$fans
vax symb.ext $$fans
vax text.ext $$fans
;
vax brexpr.x86 $$fans
vax cmsubr.x86 $$fans
vax dline.x86 $$fans
vax expr.x86 $$fans
vax instr.x86 $$fans
vax pseud1.x86 $$fans
vax pseud2.x86 $$fans
vax symb.x86 $$fans
;
vax bnf.tex $$fans
;
vax c86lnk.asm $$fans
;
;
;
;
dir a:
;
;
sdir a:
;
;
;