;MP/M-86 VAX utility backup b: disk #4 - asm86 source - more on disk #5
;
;writes on drive B, beware !
;
;up load plm-86 source, include files and submit files
;that compile into MP/M-86 utilities on the VAX 
;
;log into FRANK on the VAX before running this submit
;
user 0
mode b 0
dskreset
b:
;
vax $$a\set def [frank.mpm86.asm86]\
;
vax brexpr.plm $$fans
vax cm.plm $$fans
vax cm2.plm $$fans
vax cmac1.plm $$fans
vax cmac2.plm $$fans
vax cmac3.plm $$fans
vax cmac4.plm $$fans
vax cmac5.plm $$fans
vax cmsubr.plm $$fans
vax dline.plm $$fans
vax ermod.plm $$fans
vax expr.plm $$fans
vax files.plm $$fans
vax global.plm $$fans
vax instr.plm $$fans
vax io.plm $$fans
vax mainp.plm $$fans
vax mnem1.plm $$fans
vax mnem2.plm $$fans
vax mnem3.plm $$fans
vax mnem4.plm $$fans
vax outp.plm $$fans
vax predef.plm $$fans
vax print.plm $$fans
vax pseud1.plm $$fans
vax pseud2.plm $$fans
;
;
dir
;
;
sdir

