;MP/M-86 VAX utility backup disk #1 - mixed code and data programs
;
;writes on drive B, beware !
;
;up load plm-86 source, include files and submit files
;that compile into MP/M-86 utilities on the VAX 
;
;log into FRANK on the VAX before running this submit
;
user 0
mode b 0
dskreset
b:
;
vax $$a\set def [frank.mpm86.mixcd]\
;
vax abort.plm $$fans
vax attach.plm $$fans
vax cons.plm $$fans
vax dir.plm $$fans
vax dskrst.plm $$fans
vax era.plm $$fans
vax eraq.plm $$fans
vax ren.plm $$fans
vax set.plm $$fans
vax show.plm $$fans
vax spool.plm $$fans
vax sspool.plm $$fans
vax tod.plm $$fasn
vax type.plm $$fans
;
vax mcd.a86 $$fans
;
vax mixall.com $$fans
vax mpmcmd.com $$fans
;
vax ccb.lit $$fans
vax comlit.lit $$fans
vax copyrt.lit $$fans
vax flag.lit $$fans
vax mdsat.lit $$fans
vax proces.lit $$fans
vax qd.lit $$fans
vax sd.lit $$fans
vax uda.lit $$fans
vax vaxcmd.lit $$fans
;
;
dir
;
;
sdir
