;MP/M-86 VAX utility backup disk#5 - asm86 source - also on disk #4
;
;writes on drive B, beware !
;
;up load plm-86 source, include files and submit files
;that compile into MP/M-86 utilities on the VAX 
;
;log into FRANK on the VAX before running this submit
;
user 0
mode b 0
dskreset
b:
;
vax $$a\set def [frank.mpm86.asm86]\
;
vax asm86all.com $$fans
;
vax scan.plm $$fans
vax subr1.plm $$fans
vax subr2.plm $$fans
vax symb.plm $$fans
vax text.plm $$fans
;
vax cm.lit $$fans
vax cmac.lit $$fans
vax cmacd.lit $$fans
vax dev.lit $$fans
vax equals.lit $$fans
vax ermod.lit $$fans
vax macro.lit $$fans
vax mnem.lit $$fans
vax outp.lit $$fans
vax struc.lit $$fans
;
vax cm.ext $$fans
vax cm2.ext $$fans
vax cmlink.ext $$fans
vax cmsubr.ext $$fans
vax dline.ext $$fans
vax ermod.ext $$fans
vax exglob.ext $$fans
vax expr.ext $$fans
vax files.ext $$fans
vax global.ext $$fans
vax instr.ext $$fans
vax io.ext $$fans
vax mglob.ext $$fans
vax mnem.ext $$fans
vax outp.ext $$fans
vax predef.ext $$fans
vax print.ext $$fans
vax pseud1.ext $$fans
vax pseud2.ext $$fans
vax scan.ext $$fans
vax subr1.ext $$fans
vax subr2.ext $$fans
vax symb.ext $$fans
vax text.ext $$fans
;
vax brexpr.x86 $$fans
vax cmsubr.x86 $$fans
vax dline.x86 $$fans
vax expr.x86 $$fans
vax instr.x86 $$fans
vax pseud1.x86 $$fans
vax pseud2.x86 $$fans
vax symb.x86 $$fans
;
vax bnf.tex $$fans
;
vax c86lnk.asm $$fans
;
;
dir
;
;
sdir
