;
;Compile all MP/M-86 utilities on VAX.
;
;This submit assumes you are
;running MP/M II on a micro with a VAX link,
;and are logged into [FRANK] on the VAX 
;
;Parameters $1 $2 $3 are to PLM86 compiler.
;If specifing the XREF option to the compiler, make it param $3,
;since the ASM86.CMD plm modules already have XREF specified.
;Compilation of ASM86.CMD is fired off via the coma86.sub submit.
;
$include commix $1 $2 $3
;
$include comsep $1 $2 $3
;
$include comgs $1 $2 $3
;
$include comsdir $1 $2 $3
;
$include comsts $1 $2 $3
;
$include coma86 $1 $2
