;login into frank on VAX before running this submit
;
;generate CMD files for mixed code and data utilities
;for MP/M-86 2.0, after H86 files have been created on VAX
;
;
vax $$a\set def [frank.mpm86.mixcd]\
;
vax abort.h86 $$fans
gencmd abort
;
vax attach.h86 $$fans
gencmd attach
;
vax cons.h86 $$fans
era console.h86
ren console.h86=cons.h86
gencmd console
;
vax dir.h86 $$fans
gencmd dir
;
vax dskrst.h86 $$fans
era dskreset.h86
ren dskreset.h86=dskrst.h86
gencmd dskreset
;
vax era.h86 $$fans
gencmd era
;
vax eraq.h86 $$fans
gencmd eraq
;
vax ren.h86 $$fans
gencmd ren
;
vax set.h86 $$fans
gencmd set
;
vax show.h86 $$fans
gencmd show
;
vax spool.h86 $$fans
gencmd spool
;
vax sspool.h86 $$fans
era stopsplr.h86
ren stopsplr.h86=sspool.h86
gencmd stopsplr
;
vax tod.h86 $$fans
gencmd tod
;
vax type.h86 $$fans
gencmd type
;
vax $$a\set def [frank.mpm86.gensys]\
vax gensys.h86 $$fans
gencmd gensys
;
vax $$a\set def [frank.mpm86.mpmstat]\
vax stsrsp.h86 $$fans
gencmd stsrsp
era mpmstat.rsp
ren mpmstat.rsp=stsrsp.cmd
vax stscmd.h86 $$fans
gencmd stscmd
era mpmstat.cmd
ren mpmstat.cmd=stscmd.cmd
