.TH ASZ8K 1 local
.SH NAME
asz8k \- Z8000 assembler
.SH SYNOPSIS
.B asz8k
[
.B \-lux
]
.RB name .z8k
.br
.B asz8s
[
.B \-lux
]
.RB name .z8s
.SH DESCRIPTION
.I Asz8k
is an assembler for the Z8002 and Z8001, respectively.
They are actually two links to the same program; the name determines
the kind of code which is generated.
The source file
.IB name .z8k
or
.IB name .z8s
is assembled and the object output is left on the file
.IB name .obj\fR,
in the Unidot object file format.
.PP
The following options are supported:
.IP \fB\-l
Generate an assembly listing on the file
.IB name .lst\fR.
The
.B \-x
option implies this.
.IP \fB\-u
Treat all undefined symbols in the assembly as global.
.IP \fB\-x
Generate assembly and cross reference listings on the file
.IB name .lst\fR.
This option implies the
.B \-l
option.
.SH FILES
.IP "/usr/bin/asz8k, /usr/bin/asz8s"
Assembler program (two links to one file).
.IP "/usr/lib/asz8k.pd, /usr/lib/asz8s.pd"
Symbol and opcode definitions (two links to one file).
.SH SEE ALSO
xcon(1)
.br
.I Unidot Cross Assembler Family Programmer's Reference
.br
.I Unidot Universal Link Editor Programmer's Reference
.SH DIAGNOSTICS
Assembly errors are flagged by single-character diagnostics at the left
side of the listing.
Lines containing errors are printed on the standard output regardless
of whether a listing is enabled.
The possible errors are:
.sp
A	Macro argument error
.br
C	Conditional assembly error
.br
E	Expression error
.br
L	Label error
.br
M	Multiply defined symbol
.br
O	Opcode error
.br
P	Phase error
.br
S	Syntax error
.br
U	Undefined symbol
