.TH XCON 1 local
.SH NAME
xcon \- convert Unidot Z8000 object file to x.out format
.SH SYNOPSIS
.B xcon
[
.B \-o
outfile
] [
.B \-s
]
.RB file .obj
.SH DESCRIPTION
.I Xcon
reads the Unidot object file
.IB file .obj
and outputs the equivalent file in x.out format.
If the
.B \-o
option is given, the output goes to the specified
.IR outfile ;
otherwise the default
.B x.out
is used.
The output file is executable if it contains no unresolved external
references.
.PP
.I Xcon
marks its output file as segmented if it encounters any Z8001-only
relocation entries during the conversion; otherwise the output
is marked as non-segmented.
The
.B \-s
option will force a segmented output file regardless of the input.
.SH FILES
x.out
.SH SEE ALSO
asz8k(1), x.out(5)
.SH DIAGNOSTICS
Self-explanatory.
