

                         Frank Holsworth
                    xP/NET-86 Project Manager
                        16 December 1981



                             Charter
                             -------

†††††- Manage the design and implementation of the xP/NET-8∂
       product family until they are an‰ maintainablÂ products.

†††††- Perform Product Management of the xP/NET-86 products

†††††- MaintaiÓ† · rapporÙ witË thÂ MP/M-8∂ an‰ MP/Õ† I…† ProjecÙ ç
†††††  Managers¨† an‰† becomÂ · communicationÛ channeÏ foÚ problemÛ ç
†††††  an‰ solutionÛ thaÙ arÂ commoÓ amongsÙ MP/M's.


                              Goals
                              -----
By Today (16 Dec 1981)

     General Ideas and options developed about xP/NET-86 products
     VERY Preliminary xP/NET-86 Design Overview

One Week (21 Dec 1981)

     Seminar notes completed
     Preliminary xP/NET-86 Product Plan

.paä                          Action Items
                          ------------

[ ] Seminar Notes for MP/M-86 by 21 December 1981

[ ] xP/NET-86 Product Plan

[ ] xP/NET-86 Functional Specification

[ ] xP/NET-86 Design Specification

[ ] CP/M-86 Plus design with Danny

[ ] Get a Passport

[ ] Find out about December trip to East Coast

[ ] Get Status of a new Network programmer

[ ] discuss Mitsubishi obligations with TOM

[ ] Encourage quick decision about implementation language
