CC = c68
OBJS = main.o symt.o
CFLAGS = -L -r -DMC68000
LIB68 = -l6

lo68: $(OBJS)
	@mkver -e "lo68 -"
	${CC} ${CFLAGS} -n ${OBJS} version.c -o lo68.4k ${LIB68}
	@setstack lo68.4k 8000 8000; size lo68.2k
