$ set noon
$ vsend BIOS.C
$ vsend BIOSA.S
$ vsend BIOSTYPE.H
$ vsend BIOSTYPS.H
$ vsend BOOTER.S
$ vsend ELDBIOS.S
$ vsend ERGBIOS.S
$ vsend LCPM.SUB
$ vsend LDBIOSA.S
$ vsend LOADBIOS.H
$ vsend LOADBIOS.SUB
$ vsend MAKELDR.SUB
$ vsend NORMBIOS.H
$ vsend NORMBIOS.SUB
$ vsend PUTBOOT.S
$ vsend RELCPM.SUB
$ vsend UP1.SUB
$ vsend VMAKE.COM
$ vsend done
