$ set noon
$ vsend CANON.C
$ vsend CGEN.H
$ vsend CODEGEN.C
$ vsend CSKEL.H
$ vsend CSKELS.C
$ vsend ICODE.H
$ vsend INIT.C
$ vsend INTERF.C
$ vsend LINK.SUB
$ vsend LIST.COM
$ vsend MACHINE.11
$ vsend MACHINE.68K
$ vsend MACHINE.H
$ vsend MACHINE.VAX
$ vsend MAIN.C
$ vsend MAKE.SUB
$ vsend OPTAB.C
$ vsend PUTEXPR.C
$ vsend SEND13.SUB
$ vsend SMATCH.C
$ vsend SUCOMP.C
$ vsend TABL.C
$ vsend UP13.SUB
$ vsend UTIL.C
$ vsend VERSION.C
$ vsend VMAKE.COM
$ vsend done
