$ set noon
$ vsend AS68.H
$ vsend AS68INIT.
$ vsend AS68INIT.C
$ vsend COUT.H
$ vsend CTYPE.H
$ vsend DIR.C
$ vsend EXPR.C
$ vsend LIST.COM
$ vsend MACHINE.11
$ vsend MACHINE.68K
$ vsend MACHINE.H
$ vsend MACHINE.VAX
$ vsend MAIN.C
$ vsend MAKE.SUB
$ vsend MISC.C
$ vsend PASS1A.C
$ vsend PASS2.C
$ vsend RELINK.SUB
$ vsend STRNCMP.C
$ vsend SYMT.C
$ vsend UP9.SUB
$ vsend VERSION.C
$ vsend VMAKE.COM
$ vsend VRELINK.COM
$ vsend done
