isdd
plm80 :f1:mpmldr.plm pagewidth(80) debug
asm80 :f1:ldmonx.asm pagewidth(80) debug
link :f1:mpmldr.obj,:f1:ldmonx.obj,plm80.lib to :f1:mpmldr.mod
locate :f1:mpmldr.mod stacksize(48) code(0100h)
objhex :f1:mpmldr to :f1:mpmldr.hex
cpm
pip lst:=b:mpmldr.lst
pip lst:=b:ldmonx.lst
objcpm b:mpmldr
pip lst:=b:mpmldr.sym[pt8]
pip lst:=b:mpmldr.lin[pt8]
era b:*.lst
era b:*.sym
era b:*.lin
mac b:ldrbdos $$pp+s
mac b:ldrbios $$pp+s
pip b:mpmldr.hex=b:mpmldr.hex[I],b:ldrbdos.hex[I],b:ldrbios.hex[H]
load b:mpmldr
