isdd
plm80 :f1:mpmldr.plm pagewidth(80) debug
;asm80 :f1:ldmonx.asm pagewidth(80) debug nolist
link :f1:mpmldr.obj,:f1:ldmonx.obj,plm80.lib to :f1:mpmldr.mod
locate :f1:mpmldr.mod stacksize(48) code(0100h)
objhex :f1:mpmldr to :f1:impmldr.hex
cpm
objcpm b:mpmldr
;pip lst:=b:mpmldr.lst
;era b:*.lst
;pip lst:=b:mpmldr.sym[pt8]
;pip lst:=b:mpmldr.lin[pt8]
;mac b:ldrbdos $$pzsz
;mac b:ldrbios $$pzsz
pip b:mpmldr.hex=b:impmldr.hex[I],b:ldrbdos.hex[I],b:ldrbios.hex[H]
load b:mpmldr
