era b:*.lst
era b:*.lin
era b:*.sym
era b:*.bak
isdd
plm80 :f1:$1.plm pagewidth(80) debug
link :f1:$1.obj,:f1:x0100,plm80.lib to :f1:$11.mod
link :f1:$1.obj,:f1:x0200,plm80.lib to :f1:$12.mod
locate :f1:$11.mod code(0100H) stacksize(100)
locate :f1:$12.mod code(0200H) stacksize(100)
objhex :f1:$11 to :f1:$11.hex
objhex :f1:$12 to :f1:$12.hex
cpm
objcpm b:$11
era b:$1*.mod
era b:$1*.
pip b:$1.hex=b:$11.hex,b:$12.hex
era b:$11.hex
era b:$12.hex
genmod b:$1.hex b:$1.prl
era b:*.hex
pip lst:=b:$1.lst
pip lst:=b:$11.sym[pt8]
pip lst:=b:$11.lin[pt8]
